### ISSUE TITLE
Port to python3

### ISSUE THREAD

**Issue by innir** [thiagoralves/OpenPLC_v3#99] opened 2019-11-20 07:55 UTC
Hi,

it seems to be quite trivial to port OpenPLC to Python3. I ran `2to3` and there where only some brackets added to `print` statements and the like. The only real changes to be made where removing lines
https://github.com/thiagoralves/OpenPLC_v3/blob/master/webserver/webserver.py#L2183-L2184
as Python3 is UTF-8 anyway.
Should I create a PR?

**Comment by thiagoralves** [comment] 2019-11-20 13:50
The webserver on the runtime is simple to port, as I wrote it thinking
about Py3. The problem is with the Editor. Its codebase is quite old and
rely on old libraries. If I port the runtime to Py3, it might generate
incompatibilities on systems that need to run the Editor in Py2 at the same
machine. That being said, feel free to create the PR. Just make sure that
all the dependencies on the installer (background_installer.sh) are changed
appropriately. Thanks!

**Comment by innir** [comment] 2019-11-20 16:58
@thiagoralves I created a PR against the development branch now: https://github.com/thiagoralves/OpenPLC_v3/pull/100.

I don't think using Python 3 for the runtime does any harm for the editor, even if run on the same machine as the don't directly exchange Python data structures.

**Comment by innir** [comment] 2019-11-21 12:06
@thiagoralves Sorry, the PR was not complete :-(

In Python 3 `socket.send` accepts only bytes and `subprocess.Popen` seems to behave differently as well.

I'll follow up with a new PR

**Comment by innir** [comment] 2019-11-21 22:07
This should do the trick: #102

**Comment by garretfick** [comment] 2019-11-29 18:51
@innir I think this is now merged. Can you confirm so that this can be closed?

**Closed** 2019-11-29 19:52 UTC
